Iter13
90amper/metmon pull request #13
Opened 2023-07-18 21:54 UTC by 90amper

2023-07-20 11:20 UTC, rktkov requested changes

2023-07-20 11:20 UTC, rktkov commented on internal/storage/inmem/inmem.go
> +func (s *MemStorage) BatchAdd(ms []models.Metric) error {
AddBatch звучит лучше.

2023-07-20 11:20 UTC, rktkov commented on internal/server/server.go
> +	"github.com/90amper/metmon/internal/storage/sqlbase"
Внутренние и внешние блоки надо бы разделить

2023-07-20 11:20 UTC, rktkov commented on internal/agent/sender/sender.go
> +	basePath := "updates/"
Способ передачи данных для отправки между сборщиком и отправщиком надо переделать и использовать каналы, а не разделяемую память (поле Storage структур Collector и Sender)

2023-07-29 08:40 UTC, 90amper commented on internal/storage/inmem/inmem.go
> +func (s *MemStorage) BatchAdd(ms []models.Metric) error {
Имеется в виду Batch Addition, но Add Batch тоже подходит)

2023-07-29 08:41 UTC, 90amper commented on internal/server/server.go
> +	"github.com/90amper/metmon/internal/storage/sqlbase"
Импорты сортирует\проверяет плагин к IDE, автоматом, что-то менять бесполезно, отключать тоже не хочется

2023-07-29 08:42 UTC, 90amper commented on internal/agent/sender/sender.go
> +	basePath := "updates/"
Попробую в следующем спринте, когда пройдём каналы

2023-07-30 09:17 UTC, rktkov commented on internal/server/server.go
> +	"github.com/90amper/metmon/internal/storage/sqlbase"
Если ты между блоками оставишь пустую строку, то плагин будет сортировать каждый блок отдельно и без их смешивания.

2023-07-30 09:17 UTC, rktkov approved these changes

2023-07-31 23:05 UTC, merged