Iter5
90amper/metmon pull request #5
Opened 2023-06-11 00:47 UTC by 90amper

2023-06-12 10:22 UTC, rktkov requested changes

2023-06-12 10:22 UTC, rktkov commented on internal/storage/storage.go
> +	// GetCurrentCounterMetric(mName string) (models.Counter, error)
Не используемый код удаляем, а не комментируем. ГОшники не любят "крошки" на столе ))

2023-06-12 10:22 UTC, rktkov commented on internal/server/handlers/handlers.go
> +	"github.com/90amper/metmon/internal/storage"
Импорты надо группировать везде, а не только в выборочных местах. Консистентность надо сохранять.

2023-06-12 10:22 UTC, rktkov commented on internal/server/handlers/handlers.go
> +type Wrapper struct {
Я бы переименовал, это не обертка - это обработчик.

2023-06-12 10:22 UTC, rktkov commented on internal/server/handlers/handlers.go
> +		w.WriteHeader(http.StatusNotFound)
А почему бы не прокомментировать, что не нашел.

2023-06-12 10:22 UTC, rktkov commented on internal/models/models.go
> +// type CounterList map[string]Counter
Крошки

2023-06-12 21:26 UTC, 90amper commented on internal/server/handlers/handlers.go
> +	"github.com/90amper/metmon/internal/storage"
Это не я, это IDE) При сохранении проверяет и переписывает импорты

2023-06-14 16:40 UTC, rktkov commented on internal/server/handlers/handlers.go
> +	"github.com/90amper/metmon/internal/storage"
Стоит перенастроить ИДЕ.

2023-06-14 16:43 UTC, rktkov approved these changes

2023-06-14 16:43 UTC, rktkov commented on internal/storage/inmem/inmem.go
> +func NewInMem() *MemStorage {
NewInMem что? Storage. Стоит давать полные имена, так код читать легче.

2023-06-14 16:43 UTC, rktkov commented on internal/server/server.go
> +		panic("FileServer does not permit any URL parameters.")
Не стоит тут аварийно завершать приложение, лучше вернуть ошибку. А вызывающий код пусть принимает решение, как ошибку обрабатывать.

2023-06-14 16:43 UTC, rktkov commented on internal/server/server.go
> +	srv.FsPath = wdPath + "\\..\\..\\internal\\server\\html"
Вторую часть пути лучше тоже куда в вынести, можно начать с константы, а можно и в конфигурацию.

2023-06-15 04:55 UTC, merged