Iter9
90amper/metmon pull request #9
Opened 2023-06-28 16:25 UTC by 90amper

2023-06-30 09:43 UTC, rktkov requested changes

2023-06-30 09:43 UTC, rktkov commented on internal/storage/storage.go
> +	SaveToFile() error
Это методы и действия нужные только в файловом хранилище, лучше их внести внутрь и реализовать логику вызова внутри самого хранилища и не перекладывать ее на клиента.

2023-06-30 09:43 UTC, rktkov commented on internal/middleware/compress.go
> +type compressWriter struct {
Я бы вынес эту часть в отдельный вспомогательный пакет, а тут оставил бы только реализацию мидлвари.

2023-06-30 09:43 UTC, rktkov commented on internal/agent/sender/sender.go
> +// func Compressor(req *http.Request) {
Неиспользуемый код удаляем.

2023-06-30 09:43 UTC, rktkov commented on internal/agent/sender/sender.go
> +	// json, err := json.Marshal(body)
см. комментарий выше.

2023-06-30 09:43 UTC, rktkov commented on internal/server/handlers/handlers.go
> +	// templFile, err := os.ReadFile(hl.fsPath + "\\index.html")
Удаляем.

2023-07-04 13:14 UTC, 90amper commented on internal/storage/storage.go
> +	SaveToFile() error
Хорошо! Но тогда попозже, когда будем подключать СУБД. Как раз буду перерабатывать методы интерфейса.

2023-07-04 13:52 UTC, 90amper commented on internal/agent/sender/sender.go
> +// func Compressor(req *http.Request) {
^[ \f\t\v]*//.*\n
[ ]//.*$

:)

2023-07-06 11:22 UTC, rktkov approved these changes

2023-07-06 11:37 UTC, merged